PRESENT_SYMBOL = "✅"
ABSENT_SYMBOL = "❌"
CANCELLATION_SYMBOL = "🚫"

SIGN_UP_SYMBOL="✅"
DROP_OUT_SYMBOL="❌"

# "Ban"anas constants
ABSENT_POINTS = 3
LAST_MINUTE_CANCELLATION_POINTS = 1
BAN_THRESHOLD = 3
BAN_POINTS_ROLLOVER = True
BAN_DURATION_SESSIONS = 1
PENALISE_REGULARS = False
PENALISE_NON_REGULARS = True
PENALISE_STANDINS = False

# Logistics constants
MAX_PEOPLE_PER_SESSION = 24